#!/bin/sh

NAME=kubos-telemetry
PROG=/usr/sbin/${NAME}
PID=/var/run/${NAME}.pid


case "$1" in
    start)
	echo "Starting ${NAME}: "
	start-stop-daemon -S -q -m -b -p ${PID} --exec ${PROG}
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	echo "Stopping ${NAME}: "
	start-stop-daemon -K -q -p ${PID}
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	"$0" stop
	sleep 1
	"$0" start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	;;
esac
