#!/bin/sh
#
# Copyright (C) 2017 Kubos Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Kubos Linux Boot Finalization
#

# Update the U-Boot variables to indicate that we have successfully booted
fw_setenv kubos_curr_tried 0
fw_setenv bootcount 0
sync

# Make sure the default user's home directory exists
mkdir -p /home/kubos
chown -R kubos /home/kubos

exit 0
