#!/bin/sh

NAME=scheduler-service
PROG=/usr/sbin/${NAME}
PID=/var/run/${NAME}.pid

case "$1" in
    start)
    echo "Starting ${NAME}: "
    start-stop-daemon -q -m -b -p ${PID} --exec ${PROG} -S -- -b
    rc=$?
    if [ $rc -eq 0 ]
    then
        echo "OK"
    else
        echo "FAIL" >&2
    fi
    ;;
    stop)
    echo "Stopping ${NAME}: "
    start-stop-daemon -K -q -p ${PID}
    rc=$?
    if [ $rc -eq 0 ]
    then
        echo "OK"
    else
        echo "FAIL" >&2
    fi
    ;;
    restart)
    "$0" stop
    "$0" start
    ;;
    *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac

exit $rc