#!/bin/sh

# Start the Pumpkin MCU service in the background 
# passing in the location of the config.toml file 
# (in the same directory as the service)
python /usr/sbin/pumpkin-mcu-service/service.py -c /home/system/etc/config.toml &

exit 0
